export const actionsConstants = {
  GET_USER_DETAILS_START: "user/GET_DETAILS_START",
  GET_USER_DETAILS_FULFILLED: "user/GET_DETAILS_FULFILLED",
  GET_USER_DETAILS_FAILED: "user/GET_DETAILS_FAILED",

  UPDATE_REALTOR_START: "realtor/UPDATE_START",
  UPDATE_REALTOR_FULFILLED: "realtor/UPDATE_FULFILLED",
  UPDATE_REALTOR_FAILED: "realtor/UPDATE_FAILED",
  GET_REALTOR_MESSAGES_START: "realtor/GET_MESSAGES_START",
  GET_REALTOR_MESSAGES_FULFILLED: "realtor/GET_MESSAGES_FULFILLED",
  GET_REALTOR_MESSAGES_FAILED: "realtor/GET_MESSAGES_FAILED",
  UPDATE_REALTOR_MESSAGE_READ_STATUS: "realtor/UPDATE_MESSAGE_READ_STATUS",

  UPDATE_MESSAGE_DETAILS_START: "message/GET_DETAILS_START",
  UPDATE_MESSAGE_DETAILS_FULFILLED: "message/GET_DETAILS_FULFILLED",
  UPDATE_MESSAGE_DETAILS_FAILED: "message/GET_DETAILS_FAILED",
};
